### ISSUE TITLE
CUDA error 

### ISSUE THREAD

**Issue by wnuma16** [dynexcoin/DynexSolve#1]
I have a mining rig with AMD cards, when I start the miner I get the following error

GPUassert: CUDA driver version is insufficient for CUDA runtime version kernel.cu 1888

**Comment by oseart55** [comment]
> I have a mining rig with AMD cards, when I start the miner I get the following error
> 
> GPUassert: CUDA driver version is insufficient for CUDA runtime version kernel.cu 1888

@jumendez16  AMD cards cannot run CUDA, it is NVIDIA specific. If you do not have NVIDIA cards, you will have to wait until an OpenCL miner becomes available.

**Comment by dynexcoin** [comment]
This version only supports NVIDIA based GPUs.
