### ISSUE TITLE
rig with 12 GPU all time this error linux 

### ISSUE THREAD

**Issue by AlexSpain** [dynexcoin/DynexSolve#4]
Ubuntu 
8Gb RAM
12 GPU

05-12-2022 07:17:08 [MALLOB] CAPACITY NOTIFICATION SENT
[JSONXX] expression 'has<T>(key)' failed at jsonxx.h:400 -> dynexsolve: jsonxx.cc:30: void jsonxx::assertion(const char*, int, const char*, bool): Assertion `0' failed.

**Comment by dynexcoin** [comment]
Resolved in version 2.1.1
