### ISSUE TITLE
kernel.cu error

### ISSUE THREAD

**Issue by catursawah** [dynexcoin/DynexSolve#5]
kernel.cu:88:10: fatal error: auth.cpp: No such file or directory
 #include "auth.cpp"
          ^~~~~~~~~~
compilation terminated.

**Comment by vlasinus** [comment]
ubuntu 18.04 same problem.
---------------
#$ _SPACE_= 

#$ _CUDART_=cudart
#$ _HERE_=/usr/lib/nvidia-cuda-toolkit/bin
#$ _THERE_=/usr/lib/nvidia-cuda-toolkit/bin
#$ _TARGET_SIZE_=
#$ _TARGET_DIR_=
#$ _TARGET_SIZE_=64
#$ NVVMIR_LIBRARY_DIR=/usr/lib/nvidia-cuda-toolkit/libdevice
#$ PATH=/usr/lib/nvidia-cuda-toolkit/bin:./:/hive/bin:/hive/sbin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
#$ LIBRARIES=  -L/usr/lib/x86_64-linux-gnu/stubs
#$ gcc -std=c++14 -c -x c++ -D__NVCC__  -O4 -D"__CUDACC_VER_BUILD__=85" -D"__CUDACC_VER_MINOR__=1" -D"__CUDACC_VER_MAJOR__=9" -m64 -o "/tmp/tmpxft_00004bee_00000000-8_ip_sockets.o" "ip_sockets.cpp" 
#$ gcc -std=c++14 -c -x c++ -D__NVCC__  -O4 -D"__CUDACC_VER_BUILD__=85" -D"__CUDACC_VER_MINOR__=1" -D"__CUDACC_VER_MAJOR__=9" -m64 -o "/tmp/tmpxft_00004bee_00000000-9_portability_fixes.o" "portability_fixes.cpp" 
#$ gcc -std=c++14 -c -x c++ -D__NVCC__  -O4 -D"__CUDACC_VER_BUILD__=85" -D"__CUDACC_VER_MINOR__=1" -D"__CUDACC_VER_MAJOR__=9" -m64 -o "/tmp/tmpxft_00004bee_00000000-10_tcp_sockets.o" "tcp_sockets.cpp" 
#$ gcc -std=c++14 -c -x c++ -D__NVCC__  -O4 -D"__CUDACC_VER_BUILD__=85" -D"__CUDACC_VER_MINOR__=1" -D"__CUDACC_VER_MAJOR__=9" -m64 -o "/tmp/tmpxft_00004bee_00000000-11_dprintf.o" "dprintf.cpp" 
#$ gcc -std=c++14 -c -x c++ -D__NVCC__  -O4 -D"__CUDACC_VER_BUILD__=85" -D"__CUDACC_VER_MINOR__=1" -D"__CUDACC_VER_MAJOR__=9" -m64 -o "/tmp/tmpxft_00004bee_00000000-12_jsonxx.o" "jsonxx.cc" 
#$ gcc -std=c++14 -c -x c++ -D__NVCC__  -O4 -D"__CUDACC_VER_BUILD__=85" -D"__CUDACC_VER_MINOR__=1" -D"__CUDACC_VER_MAJOR__=9" -m64 -o "/tmp/tmpxft_00004bee_00000000-13_Dynexchip.o" "Dynexchip.cpp" 
#$ gcc -std=c++14 -D__CUDA_ARCH__=300 -E -x c++  -DCUDA_DOUBLE_MATH_FUNCTIONS -D__CUDACC__ -D__NVCC__  -O4 -D"__CUDACC_VER_BUILD__=85" -D"__CUDACC_VER_MINOR__=1" -D"__CUDACC_VER_MAJOR__=9" -include "cuda_runtime.h" -m64 "kernel.cu" > "/tmp/tmpxft_00004bee_00000000-14_kernel.cpp1.ii" 
kernel.cu:88:20: fatal error: auth.cpp: No such file or directory

                    ^
compilation terminated.
# --error 0x1 --

**Comment by nitrogenium** [comment]
Any solutions ?

**Comment by connquistador** [comment]
anyone get this figured out yet?

**Comment by dynexcoin** [comment]
resolved with latest release

**Comment by vlasinus** [comment]
New error in log file
[log.txt](https://github.com/dynexcoin/DynexSolve/files/10266882/log.txt)
