### ISSUE TITLE
kernel.cu:88:10: fatal error: auth.cpp: No such file or directory

### ISSUE THREAD

**Issue by viponedream** [dynexcoin/DynexSolve#6]
nvcc ip_sockets.cpp portability_fixes.cpp tcp_sockets.cpp dprintf.cpp jsonxx.cc Dynexchip.cpp auth.cpp kernel.cu -o dynexsolve -O4 -lcurl libCrypto.a;

there's a error 
kernel.cu:88:10: fatal error: auth.cpp: No such file or directory

**Comment by dynexcoin** [comment]
resolved with latest release
